version: '3'
services:
  back-end:
    build:
      context: hallo-app-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks: 
      hallonet:
        ipv4_address: 10.5.0.5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/centos/smru_audio:/home/centos/smru_audio
    environment: # 172.17.0.1
      - spring.datasource.url=jdbc:postgresql://host.docker.internal:0/hallo
      - spring.datasource.username=development
      - spring.datasource.password=USE_YOUR_OWN_PASSWORD
      - spring.profiles.active=prod
    restart: unless-stopped

  front-end:
    build:
      context: hallo-app-frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks: 
      hallonet:
        ipv4_address: 10.5.0.6
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
    depends_on:
      - back-end
    restart: unless-stopped

networks:
  hallonet:
    driver: bridge
    name: hallonet
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
