services:
  back-end:
    build:
      context: hallo-app-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080

    volumes:
      - /Users/***REMOVED***/Desktop/hallo/audio:/audio/live/smru/
    environment:
      - spring.datasource.url=jdbc:postgresql://host.docker.internal:0/hallo
      - spring.datasource.username=username
      - spring.datasource.password=USE_YOUR_OWN_PASSWORD
      - spring.profiles.active=prod

    
  front-end:
    build:
      context: hallo-app-frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      # - ./certbot/www:/var/www/certbot/:ro
      # - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - back-end
  
