services:
  back-end:
    build:
      context: hallo-app-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080

    volumes:
      - /Users/***REMOVED***/Desktop/hallo/audio:/Users/***REMOVED***/Desktop/hallo/audio
    environment:
      - spring.datasource.url=jdbc:postgresql://host.docker.internal:0/hallo
      - spring.datasource.username=username
      - spring.datasource.password=USE_YOUR_OWN_PASSWORD
      - spring.profiles.active=prod

    
  front-end:
    build:
      context: hallo-app-frontend
      dockerfile: Dockerfile
   

    ports:
      - 3000:3000
    volumes:
      - webdata:/app/build/
    depends_on:
      - back-end
  
  web-server:
    image: nginx:mainline-alpine3.18-slim
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - webdata:/usr/share/nginx/html/:ro
      # - ./certbot/www:/var/www/certbot/:ro
      # - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - front-end
volumes:
  webdata:
